package cli

import (
	"strings"
	"testing"

	"github.com/spf13/pflag"
)

// skipAutoGenerated returns true for commands auto-generated by cobra (e.g. completion).
func skipAutoGenerated(name string) bool {
	return name == "completion" || name == "help"
}

func TestAllSubcommandsHaveLongDescription(t *testing.T) {
	for _, cmd := range rootCmd.Commands() {
		if skipAutoGenerated(cmd.Name()) {
			continue
		}
		if cmd.Long == "" {
			t.Errorf("subcommand %q has empty Long description", cmd.Name())
		}
	}
}

func TestAllSubcommandsHaveExamples(t *testing.T) {
	for _, cmd := range rootCmd.Commands() {
		if skipAutoGenerated(cmd.Name()) {
			continue
		}
		if cmd.Example == "" {
			t.Errorf("subcommand %q has no Examples set", cmd.Name())
		}
	}
}

func TestImportCommandHasAtLeast10Flags(t *testing.T) {
	flagCount := 0
	importCmd.NonInheritedFlags().VisitAll(func(f *pflag.Flag) {
		flagCount++
	})
	if flagCount < 10 {
		t.Errorf("import command has %d flags, want at least 10", flagCount)
	}
}

func TestRootHelpContainsTypicalWorkflow(t *testing.T) {
	if !strings.Contains(rootCmd.Long, "Typical workflow") {
		t.Errorf("root command Long does not contain 'Typical workflow'")
	}
}
